PythonVersion="3.7.9"
packagedir=".python_packages/lib/site-packages"
OperationId="|1RWqbxEIy04=.b3975da7_"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"